-- שליפת כל הנתונים מכל הטבלאות
SELECT * FROM VOLUNTEER;
SELECT * FROM SKILL;
SELECT * FROM TYPE;
SELECT * FROM CATAGORY;
SELECT * FROM TRAINING;
SELECT * FROM CALL;
SELECT * FROM AVAILABILITY;
SELECT * FROM SCHEDULED;
SELECT * FROM VOLUNTEER_SKILL;
SELECT * FROM VOLUNTEER_CALL;
SELECT * FROM VOLUNTEER_TRAINING;
SELECT * FROM SKILL_CATEGORY;

-- ספירת כמות הרשומות בכל טבלה
SELECT 'VOLUNTEER' AS table_name, COUNT(*) FROM VOLUNTEER;
SELECT 'SKILL' AS table_name, COUNT(*) FROM SKILL;
SELECT 'TYPE' AS table_name, COUNT(*) FROM TYPE;
SELECT 'CATAGORY' AS table_name, COUNT(*) FROM CATAGORY;
SELECT 'TRAINING' AS table_name, COUNT(*) FROM TRAINING;
SELECT 'CALL' AS table_name, COUNT(*) FROM CALL;
SELECT 'AVAILABILITY' AS table_name, COUNT(*) FROM AVAILABILITY;
SELECT 'SCHEDULED' AS table_name, COUNT(*) FROM SCHEDULED;
SELECT 'VOLUNTEER_SKILL' AS table_name, COUNT(*) FROM VOLUNTEER_SKILL;
SELECT 'VOLUNTEER_CALL' AS table_name, COUNT(*) FROM VOLUNTEER_CALL;
SELECT 'VOLUNTEER_TRAINING' AS table_name, COUNT(*) FROM VOLUNTEER_TRAINING;
SELECT 'SKILL_CATEGORY' AS table_name, COUNT(*) FROM SKILL_CATEGORY;
